allow pkgslog to accept lower levels than its wrapped handler
reugn/pkgslog pull request #3
Opened 2024-02-24 18:39 UTC by jippi

Currently the minimum log level is controlled by the wrapped handler

This change makes the pkgslog handler accept any log level (or lower) configured  for a package level.

This mean you can now have your wrapped log handler at `WARN` but turn on `DEBUG` level for a specific package and stil have those debug level messages be printed.

In my use-case, I'm using [`slog-multi`](github.com/samber/slog-multi) and a couple of other wrapped handlers like the example below, and I want to be able to adjust log level per package.

```go
		slog.New(
			slogmulti.
				Pipe(
					func(next slog.Handler) slog.Handler {
						return pkgslog.NewPackageHandler(next, packageLogLevels())
					},
				).
				Pipe(
					slogctx.NewMiddleware(&slogctx.HandlerOptions{}),
				).
				Pipe(
					slogdedup.NewOverwriteMiddleware(&slogdedup.OverwriteHandlerOptions{
						ResolveBuiltinKeyConflict: slogdedup.KeepIfBuiltinKeyConflict,
					}),
				).
				Handler(
					logHandler(stderr),
				),
		)
```

I'm controlling my log levels like this, where each package level can be controlled via ENV variables, overriding the `global` log level

```go
func pkgLogLevel(name string, fallback slog.Level) slog.Level {
	return ParseLogLevel(os.Getenv(name+"_LOG_LEVEL"), fallback)
}

func packageLogLevels() map[string]slog.Level {
	return map[string]slog.Level{
		pkgPrefix + "/pkg/parser":  pkgLogLevel("PARSER", slog.LevelWarn),
		pkgPrefix + "/pkg/scanner": pkgLogLevel("SCANNER", slog.LevelWarn),
	}
}
```

2024-02-25 07:36 UTC, reugn requested changes

2024-02-25 07:36 UTC, reugn commented on pkgslog.go
> +	}
Hi @jippi, thanks for pointing that out.

For better performance, I'd precompute the minimum log level in the constructor:
```go
        var minPkgLevel *slog.Level
	for _, pkgLevel := range packages {
		if minPkgLevel == nil || pkgLevel < *minPkgLevel {
			minPkgLevel = &pkgLevel
		}
	}
	return &PackageHandler{
		handler:     h,
		packages:    packages,
		minPkgLevel: minPkgLevel,
	}
```

And then compare with it in the Enabled method:
```go
        if h.minPkgLevel != nil && *h.minPkgLevel <= level {
		return true
	}
```

I used a pointer here to allow empty map arguments.

2024-02-25 07:45 UTC, reugn commented on pkgslog_test.go
> +	)
I would not group those two variables.

2024-03-01 09:59 UTC, reugn commented
@jippi, what are your thoughts?

2024-03-07 16:50 UTC, merged

2024-03-07 17:58 UTC, jippi commented
Sorry, I got distracted by some other OSS work and forgot to follow up - I think your suggestion makes sense :)